### PR TITLE
Fix PDF generation

### PR DESCRIPTION
**Pull request by Mogztter**
- remove built-in fonts
- fix PDF extension
- configure source highlighter and fonts

The PDF generated is slightly different. You can take a look: [index.pdf](https://github.com/mraible/jhipster-book/files/6208213/index.pdf)

### CODE REVIEW

**Comment by mraible** [comment]
I took a brief look and nothing sticks out a first glance. What are the major differences with this new version?

**Comment by Mogztter** [comment]
Asciidoctor PDF is using Noto Emoji to render emoji:

emoji2

emoji

I also noticed that the footer has a border (by default):

footer-border

If needed, I think we can remove it using:

```yaml
footer:
  border-color: transparent
```

**Comment by mraible** [comment]
Hmmmm, is there anything preventing me from using the previous emojis (that had more color)?

**Comment by Mogztter** [comment]
Colored emoji fonts are not supported in Asciidoctor PDF (or more precisely in ttfunk) and never was.
You can still use emojis in AsciiDoc but the PDF output will display non-colored emojis.

I believe that Symbola font was previously used instead or Noto Emoji but some emojis were not rendered (for instance ✨ was missing from the PDF)

**Comment by mraible** [comment]
@Mogztter I'm not sure if the issue I'm seeing today is caused by this change or another one. If I do a build of the PDF from the main branch, the cover image shows up with white lines on the side of it. The cover image used to stretch all the way across. Do you know what's causing that?

I'm seeing this issue with my Angular Mini-Book too, which doesn't have the same theme changes as this book does.

**Comment by Mogztter** [comment]
@mraible I made these changes to be compatible with the latest version of Asciidoctor PDF. I guess something has changed in Asciidoctor PDF, I will try to pinpoint in which version this change was introduced.

**Comment by Mogztter** [comment]
Found a solution: https://github.com/mraible/jhipster-book/pull/18

**Comment by mraible** [comment]
@Mogztter I just tried integrating these changes into my Angular Mini Book. When I did, I noticed it no longer renders syntax highlighting for TypeScript files. I don't see TypeScript listed [for CodeRay](https://docs.asciidoctor.org/asciidoctor/latest/syntax-highlighting/coderay/). Do you know if it's possible to add support?

**Pull request merged**
